# Generated by Django 4.0 on 2021-12-12 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_description_task_descriptions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='descriptions',
            new_name='jobdescription',
        ),
    ]
