# Generated by Django 4.0 on 2021-12-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_descriptions_task_jobdescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='complete',
        ),
        migrations.AddField(
            model_name='task',
            name='interview',
            field=models.BooleanField(default=False, verbose_name='Interview'),
        ),
        migrations.AddField(
            model_name='task',
            name='joblink',
            field=models.CharField(default='www.somelink.com', max_length=200, verbose_name='Job title'),
        ),
        migrations.AddField(
            model_name='task',
            name='rejected',
            field=models.BooleanField(default=False, verbose_name='Rejected'),
        ),
        migrations.AlterField(
            model_name='task',
            name='jobdescription',
            field=models.TextField(blank=True, null=True, verbose_name='Position Description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Job title'),
        ),
    ]
