# Generated by Django 4.0 on 2021-12-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_task_complete_task_interview_task_joblink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='joblink',
            field=models.URLField(verbose_name='Job Link'),
        ),
    ]
