# Generated by Django 4.0 on 2021-12-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_task_joblink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='joblink',
            field=models.CharField(max_length=200, verbose_name='Job Link'),
        ),
    ]
