# Generated by Django 4.0 on 2021-12-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_task_joblink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='interview',
            field=models.DateField(blank=True),
        ),
    ]
