# Generated by Django 4.0 on 2021-12-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_task_interview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='interview',
            field=models.DateField(),
        ),
    ]
