# Generated by Django 4.0 on 2021-12-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_task_interview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='interview',
            field=models.BooleanField(default=False, verbose_name='Interview'),
        ),
    ]
