# Generated by Django 4.0 on 2021-12-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_task_interview'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='interviewdate',
            field=models.DateTimeField(auto_now_add=True, default=0.0005772719775688604),
            preserve_default=False,
        ),
    ]
